### PR TITLE
7.x-1.1

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Tagging new release for socorro branch work.

# Needed By (Date)
- Before we can push socorro live.

# Urgency
- 3/10

# Steps to Test

1. Review code
2. Merge
3. Release tag following Drupal version practices
4. Release tag following Semantic version practices
5. Push commit rolling back module versions to `-dev`

# Associated Issues and/or People
- SITES-533
- SITES-642

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jbickar** [comment]
Come on, are we using this anywhere?

**Comment by sherakama** [comment]
Yes, jumpstart-vpsa uses it.

https://github.com/SU-SWS/stanford-jumpstart-deployer/blob/7.x-4.x/make/production/jumpstart-vpsa.make#L85

**Comment by jbickar** [comment]
_FINE_

**Comment by jbickar** [comment]
[Total installs: 4](https://docs.google.com/spreadsheets/d/1rNSNxshxOwOZNgE0f_m_mBYlzk2MxTSWvJsXEIzsU3E/edit#gid=0)

**Comment by sherakama** [comment]
Aye, but new VPSA sites need to have the option to turn it on. It is part of their product even if not all of their sites turn it on.

**Comment by jbickar** [comment]
I already merged and tagged it. I've moved on.

**Pull request merged**
